config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  resources :posts do
    resources :comments
    member do
      get 'like'
      get 'unlike'
    end
  end
  
  devise_for :users, :controllers => { registrations: 'registrations' }

  get 'browse', to: 'posts#browse', as: :browse_posts
  
  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through
  get 'notifications', to: 'notifications#index'

  get 'profiles/show'
  
  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile

  post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  before_action :authenticate_user!
  before_action :owned_profile, only: [:edit, :update]
  before_action :set_user

  def show
    @posts = @user.posts
  end

  def edit
  end

  def update
    if @user.update(profile_params)
      flash[:success] = 'Your profile has been updated.'
      redirect_to profile_path(@user.user_name)
    else
      @user.errors.full_messages
      flash[:error] = @user.errors.full_messages
      render :edit
    end
  end


  private

  def set_user
    @user = User.find_by(user_name: params[:user_name])
  end

  def profile_params
    params.require(:user).permit(:avatar, :bio)
  end

  def owned_profile
    @user = User.find_by(user_name: params[:user_name])
    unless current_user == @user
      flash[:alert] = "That profile doesn't belong to you!"
      redirect_to root_path
    end
  end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def current_user_is_following(current_user_id, followed_user_id)
    relationship = Follow.find_by(follower_id: current_user_id, following_id: followed_user_id)
    return true if relationship
  end
end

app/views/profiles/edit.html.haml
.form--edit-profile
  = form_for @user, url: {action: "update"}, html: { multipart: true } do |f|
    .form--edit-profile__avatar.text-center
      %h4 Change your profile image:
      = profile_avatar_select(@user)
    .form--edit-profile__file
      = f.file_field :avatar, onChange: 'loadFile(event)'
    .form--edit-profile__bio
      %h4 Update your bio:
      = f.text_area :bio, rows: 4
    .form-group.text-center
      = f.submit "Update Profile", class: 'btn btn-success'

app/views/profiles/show.html.haml
.profile
  .row
    .col-xs-6
      = image_tag @user.avatar.url(:medium), class:'img-responsive img-circle profile__avatar'
    .col-xs-6
      %h4.profile__name=@user.user_name
      - if @user == current_user
        = link_to 'Edit Profile', edit_profile_path(@user.user_name), class: 'btn profile__action profile__action--edit'
      - else
        - if current_user_is_following(current_user.id, @user.id)
          = link_to 'Following', unfollow_user_path, remote: true, class: 'btn profile__action profile__action--unfollow', id: 'unfollow-button', method: :post
        - else
          = link_to 'Follow', follow_user_path, remote: true, class: 'btn profile__action profile__action--follow', id: 'follow-button', method: :post

      %ul.profile__stats
        %li= pluralize(@user.posts.count, 'post')
        %li= pluralize(@user.followers.count, 'follower')
        %li= "#{@user.following.count} following"

      %p.profile__bio=@user.bio

  .row.profile__posts
    %h4="#{@user.user_name}'s posts"
    -@posts.each do |post|
      = render 'posts/post', post: post