config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  resources :posts do
    resources :comments
    member do
      get 'like'
      get 'unlike'
    end
  end
  
  devise_for :users, :controllers => { registrations: 'registrations' }

  get 'browse', to: 'posts#browse', as: :browse_posts
  
  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through
  get 'notifications', to: 'notifications#index'

  get 'profiles/show'
  
  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile

  post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :notified_by, class_name: 'User'
  belongs_to :user
  belongs_to :post

  validates :user_id, :notified_by_id, :post_id, :notice_type, presence: true

  paginates_per 10

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  
  def index
    @notifications = current_user.notifications.page params[:page]
  end

  def link_through
    @notification = Notification.find(params[:id])
    @notification.update read: true
    redirect_to post_path @notification.post
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper

  def unread(notification)
    if notification.read
      return 'read'
    else
      return 'unread'
    end
  end

end

app/views/notifications/_notification.html.haml
%li{class: "notifications__item notifications__item--#{unread notification}"}
  = link_to "#{notification.notified_by.user_name} #{notification.notice_type}ed on your post", link_through_path(notification), class: "notifications__item--#{unread notification}__link"
  .notifications__item__time
    = time_ago_in_words(notification.created_at)
    ago

app/views/notifications/_notification_dropdown.html.haml
.dropdown.dropdown--notification
  %button.btn.btn-default.dropdown-toggle{ type: 'button', id: 'dropdownMenu1', data: { toggle: 'dropdown' }, 'ariahaspopup': true, 'aria-expanded': true }
    = current_user.notifications.where(read: false).count
    %span.glyphicon.glyphicon-flag
  %ul.dropdown-menu{ 'aria-labelledby': 'dropdownMenu1' }
    %li.dropdown-header.text-center Notifications
    - current_user.notifications.where(read: false).order('created_at DESC').last(5).each do |notification|
      = render 'notifications/notification_small', notification: notification
    %li.divider{ role: 'separator' }
    %li.text-center= link_to 'View All', notifications_path

app/views/notifications/_notification_small.html.haml
%li
  = link_to "#{notification.notified_by.user_name} #{notification.notice_type}ed on your post", link_through_path(notification)

app/views/notifications/_small_notification.html.haml
%li.notifications__item--small
  = link_to "#{notification.notified_by.user_name} #{notification.notice_type}ed on your post", link_through_path(notification), class: 'notifications__item--small__link'

app/views/notifications/index.html.haml
.notifications
  %h3 Notifications
  %ul{id: 'notifications'}
    = render @notifications.order('created_at DESC')
  
  - if @notifications.total_count > @notifications.default_per_page
    #paginator
      = link_to_next_page @notifications, 'Show More', remote: true, id: 'show_more'

app/views/notifications/index.js.erb
$('#notifications').append("<%= j (render @notifications.order('created_at DESC')) %>");

$('#paginator').html("<%= j (link_to_next_page(@notifications, 'Show More', remote: true, id: 'show_more'))%>")

app/views/notifications/link_through.html.erb
<h1>Notifications#link_through</h1>
<p>Find me in app/views/notifications/link_through.html.erb</p>