config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  resources :posts do
    resources :comments
    member do
      get 'like'
      get 'unlike'
    end
  end
  
  devise_for :users, :controllers => { registrations: 'registrations' }

  get 'browse', to: 'posts#browse', as: :browse_posts
  
  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through
  get 'notifications', to: 'notifications#index'

  get 'profiles/show'
  
  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile

  post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

end

app/models/post.rb
class Post < ActiveRecord::Base
  
  acts_as_votable
  
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy
  
  default_scope -> { order(created_at: :desc) }
  
  validates :user_id, presence: true
  validates :image, presence: true
  validates :caption, length: { minimum: 3, maximum: 300 }

  has_attached_file :image, styles: { :medium => "640x" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  scope :of_followed_users, -> (following_users) { where user_id: following_users }
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy, :like, :unlike]
  before_action :owned_post, only: [:edit, :update, :destroy]
  
  def index
    total_posts = (Post.of_followed_users(current_user.following) + current_user.posts).sort_by(&:created_at).reverse!
    @posts = Kaminari.paginate_array(total_posts).page params[:page]
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      flash[:success] = "Post successfully created."
      redirect_to posts_path
    else
      flash[:alert] = "Post could not be created. Please check the form."
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:success] = "Post successfully updated."
      redirect_to posts_path
    else
      flash.now[:alert] = "Update failed. Please check the form."
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  def browse
    @posts = Post.all.page params[:page]
    @posts_count = Post.all.count
  end

  def like
    if @post.liked_by current_user
      respond_to do |format|
        format.html { redirect_to :back }
        format.js
      end
    end
  end

  def unlike
    if @post.unliked_by current_user
      respond_to do |format|
        format.html { redirect_to :back }
        format.js
      end
    end
  end


  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:image, :caption)
  end

  def owned_post
    unless current_user == @post.user
      flash[:alert] = "That post doesn't belong to you!"
      redirect_to root_path
    end
  end

end

app/helpers/posts_helper.rb
module PostsHelper

  def display_likes(post)
    votes = post.votes_for.up.by_type(User)
    if votes.size > 5
      count_likers(votes)
    else
      list_likers(votes)
    end
  end

  def count_likers(votes)
    votes.size.to_s + ' people like this'
  end

  def list_likers(votes)
    user_names = []
    unless votes.blank?
      votes.voters.each do |voter|
        user_names.push(link_to voter.user_name, profile_path(voter.user_name))
      end
      user_names.to_sentence.html_safe + like_plural(votes)
    end
  end

  def liked_post_link(post)
    if current_user.voted_for? post
      unlike_post_path(post.id)
    else
      like_post_path(post.id)
    end
  end

  def liked_post_icon(post)
    if current_user.voted_for? post
      'glyphicon-heart'
    else
      'glyphicon-heart-empty'
    end
  end

  def likers_class(post)
    if post.votes_for.up.by_type(User).size > 0
      'post__likers'
    end
  end

  def comments_class(post)
    if post.comments.count > 0
      'post__comments'
    end
  end


  private

  def like_plural(votes)
    return ' like this' if votes.count > 1
    ' likes this'
  end
end

app/views/posts/_form.html.haml
.form--new-post
  = form_image_select(@post)
  = simple_form_for @post, html: { multipart: true } do |f|
    = f.error_notification
    .form-group
      = f.input :image, label: false, input_html: { onChange: 'loadFile(event)' }
    .form-group
      = f.input :caption, input_html: { class: 'form-control' }
    .form-group.text-center
      = f.button :submit, class: 'btn-success'

app/views/posts/_likes.html.haml
= display_likes post

app/views/posts/_post.html.haml
.post
  .post__caption
    = post.caption
  .post__time
    = time_ago_in_words(post.created_at)
    ago
  .post__image
    = link_to (image_tag post.image.url(:medium), class:'img-responsive'), post_path(post)
  .post__user
    %span.glyphicon.glyphicon-user{"aria-hidden" => "true"}
    = link_to post.user.user_name, profile_path(post.user.user_name)
  
  %div{id: "likers_#{post.id}", class: "#{likers_class post}"}
    = render 'posts/likes', post: post  

  %div{id: "comments_#{post.id}", class: "#{comments_class post}"}
    = render post.comments.last(4), post: post

  .post__show-comments{id: "show_comments_#{post.id}"}
    - if post.comments.count > 4
      = link_to "View all #{post.comments.count} comments", post_comments_path(post), remote: true, class: 'show-comments-link', data: {post_id: "#{post.id}", type: "html"}

  .row.post__bottom
    .col-xs-1
      .post__like
        = link_to '', liked_post_link(post), remote: true, id: "like_#{post.id}", class: "glyphicon #{liked_post_icon post}"

    .col-xs-11
      .form--comment
        = form_for([post, post.comments.build], remote: true) do |f|
          = f.text_field :content, placeholder: 'Add a comment...', id: "comment_content_#{post.id}", class: 'input-text'

app/views/posts/_post_dashboard.html.haml
#posts
  = render 'posts'

- if @posts.total_count > @posts.default_per_page
  #paginator.paginator--posts
    = link_to_next_page @posts, 'LOAD MORE', remote: true, id: 'load_more'

app/views/posts/_posts.html.haml
-@posts.each do |post|
    = render 'post', post: post

app/views/posts/browse.html.haml
= render 'post_dashboard', posts: @posts

app/views/posts/browse.js.erb
$('#posts')
  .append("<%= j (render 'posts')%>");

$('#paginator')
  .html("<%= j (link_to_next_page(@posts, 'LOAD MORE', remote: true, id: 'load_more'))%>");

if (!$('#load_more').length) { 
  $('#paginator').remove(); 
}

app/views/posts/edit.html.haml
.wrapper
    
  = render 'form'

  .row.text-center
    =link_to "Delete Post", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" }
    &nbsp|&nbsp
    =link_to "Cancel", posts_path

app/views/posts/index.html.haml
#posts
  = render 'posts'
  
- if @post_count > 3
  #paginator.paginator--posts
    = link_to_next_page @posts, 'LOAD MORE', remote: true, id: 'load_more'

app/views/posts/index.js.erb
$('#posts')
  .append("<%= j (render 'posts')%>");

$('#paginator')
  .html("<%= j (link_to_next_page(@posts, 'LOAD MORE', remote: true, id: 'load_more'))%>");

if (!$('#load_more').length) { 
  $('#paginator').remove(); 
}

app/views/posts/like.js.erb
$('#like_<%= @post.id %>').removeClass('glyphicon-heart-empty').addClass('glyphicon-heart');

$('#likers_<%= @post.id %>').addClass('post__likers');
$('#likers_<%= @post.id %>').html('<%= j (render partial: "posts/likes", locals: { post: @post } ) %>');

app/views/posts/new.html.haml
.form--new-post
  = form_image_select(@post)
  = simple_form_for @post, html: { multipart: true } do |f|
    = f.error_notification
    .form-group
      = f.input :image, label: false, input_html: { onChange: 'loadFile(event)' }
    .form-group
      = f.input :caption, input_html: { class: 'form-control' }
    .form-group.text-center
      = f.button :submit, class: 'btn-success'

app/views/posts/show.html.haml
.wrapper
  = render 'post', post: @post
  - if @post.user.id == current_user.id 
    .row
      .col-xs-12.text-center
        = link_to "Edit", edit_post_path(@post)

app/views/posts/unlike.js.erb
var like_button = $('#like_<%= @post.id %>');
var likers = $('#likers_<%= @post.id %>');

like_button
  .removeClass('glyphicon-heart')
  .addClass('glyphicon-heart-empty')
  .attr('href', '/posts/<%= @post.id %>/like');

likers
  .html('<%= j (render partial: "posts/likes", locals: { post: @post } ) %>');

if (!likers.children().size()) {
  likers.removeClass('post__likers');
}